# Generated by Django 5.2.8 on 2025-12-05 20:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enriched',
            fields=[
                ('transactionId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('transaction_type', models.IntegerField(blank=True, db_column='type', null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('nameOrig', models.CharField(blank=True, max_length=255, null=True)),
                ('oldbalanceOrg', models.FloatField(blank=True, null=True)),
                ('newbalanceOrig', models.FloatField(blank=True, null=True)),
                ('nameDest', models.CharField(blank=True, max_length=255, null=True)),
                ('oldbalanceDest', models.FloatField(blank=True, null=True)),
                ('newbalanceDest', models.FloatField(blank=True, null=True)),
                ('isFraud', models.IntegerField(blank=True, null=True)),
                ('mean_amount', models.FloatField(blank=True, null=True)),
                ('stddev_amount', models.FloatField(blank=True, null=True)),
                ('max_amount_seen', models.FloatField(blank=True, null=True)),
                ('min_amount_seen', models.FloatField(blank=True, null=True)),
                ('user_txn_count', models.IntegerField(blank=True, null=True)),
                ('txn_count_in_step', models.IntegerField(blank=True, null=True)),
                ('total_amount_in_step', models.FloatField(blank=True, null=True)),
                ('sender_out_degree', models.IntegerField(blank=True, null=True)),
                ('sender_in_degree', models.IntegerField(blank=True, null=True)),
                ('sender_fraud_ratio', models.FloatField(blank=True, null=True)),
                ('pagerank', models.FloatField(blank=True, null=True)),
                ('amount_to_profile_ratio', models.FloatField(blank=True, null=True)),
                ('amount_to_balance_ratio', models.FloatField(blank=True, null=True)),
                ('logamount', models.FloatField(blank=True, null=True)),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.IntegerField(blank=True, null=True)),
                ('origMoreSent', models.FloatField(blank=True, null=True)),
                ('destMoreRec', models.FloatField(blank=True, null=True)),
                ('origMoreSentFlag', models.IntegerField(blank=True, null=True)),
                ('destMoreRecFlag', models.IntegerField(blank=True, null=True)),
                ('trust_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enriched',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp', models.PositiveIntegerField(blank=True, null=True)),
                ('tp', models.PositiveIntegerField(blank=True, null=True)),
                ('tn', models.PositiveIntegerField(blank=True, null=True)),
                ('fn', models.PositiveIntegerField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('tpr', models.FloatField(blank=True, null=True)),
                ('fpr', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('watermark_ms', models.BigIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metrics',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('transactionId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('step', models.IntegerField()),
                ('transaction_type', models.IntegerField(db_column='type')),
                ('amount', models.FloatField()),
                ('nameOrig', models.CharField(max_length=255)),
                ('oldbalanceOrg', models.FloatField()),
                ('newbalanceOrig', models.FloatField()),
                ('nameDest', models.CharField(max_length=255)),
                ('oldbalanceDest', models.FloatField()),
                ('newbalanceDest', models.FloatField()),
                ('isFraud', models.IntegerField()),
                ('kyc_tier', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw_transactions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('account', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mean_amount', models.FloatField(blank=True, null=True)),
                ('sum_amount_sq', models.FloatField(blank=True, null=True)),
                ('max_amount_seen', models.FloatField(blank=True, null=True)),
                ('min_amount_seen', models.FloatField(blank=True, null=True)),
                ('txn_count', models.IntegerField(blank=True, null=True)),
                ('latest_step', models.IntegerField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('stddev_amount', models.FloatField(blank=True, null=True)),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('transaction', models.OneToOneField(db_column='transactionId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.enriched')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('fraud_probability', models.FloatField(blank=True, null=True)),
                ('isFraud', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.IntegerField(blank=True, null=True)),
                ('is_verified_human', models.BooleanField(blank=True, null=True)),
                ('is_verified_system', models.BooleanField(blank=True, null=True)),
                ('verification_time', models.BigIntegerField(blank=True, null=True)),
                ('ground_truth', models.IntegerField(blank=True, default=None, null=True)),
                ('is_counted_metrics', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ml_prediction',
            },
        ),
        migrations.AddIndex(
            model_name='enriched',
            index=models.Index(fields=['nameOrig'], name='enriched_nameOri_029956_idx'),
        ),
        migrations.AddIndex(
            model_name='enriched',
            index=models.Index(fields=['step'], name='enriched_step_852661_idx'),
        ),
        migrations.AddIndex(
            model_name='enriched',
            index=models.Index(fields=['isFraud'], name='enriched_isFraud_4cd3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['calculated_at'], name='metrics_calcula_e6d86f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['nameOrig'], name='raw_transac_nameOri_a10bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['step'], name='raw_transac_step_b84169_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['created_at'], name='raw_transac_created_e1fb72_idx'),
        ),
    ]
