# Generated by Django 5.2.7 on 2025-10-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('partition', models.IntegerField()),
                ('offset', models.BigIntegerField()),
                ('key', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(max_length=32)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=8)),
                ('timestamp_ms', models.BigIntegerField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
