# Generated by Django 5.1.2 on 2025-11-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionraw',
            name='currency',
        ),
        migrations.AddField(
            model_name='transactionraw',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionraw',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transactionraw',
            name='from_account',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transactionraw',
            name='geo_country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transactionraw',
            name='ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='transactionraw',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transactionraw',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionraw',
            name='to_account',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='ingestlog',
            index=models.Index(fields=['topic', 'partition', 'offset'], name='ingest_log_topic_223015_idx'),
        ),
        migrations.AlterModelTable(
            name='ingestlog',
            table='ingest_log',
        ),
        migrations.AlterModelTable(
            name='transactionraw',
            table='transaction_raw',
        ),
    ]
